name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    container:
      image: continuumio/miniconda3:23.10.0-1
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    # - name: Activate environment
    #   run: |
    #     source /opt/conda/etc/profile.d/conda.sh
    #     conda create --name ocr_project -y python=${{ matrix.python-version }}
    #     conda install gcc_linux-64 gxx_linux-64
    #     conda env update --name ocr_project --file environment.yml
    #     conda activate ocr_project
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint src --fail-under=5.0
        pylint main.py --fail-under=5.0